name: Draft PR Closer
on:
  pull_request_review_comment:
    types: [created]

jobs:
  draft_pr_close:
    runs-on: ubuntu-latest
    name: Draft PR Closer
    steps:
    - name: Get PR Status
      uses: treiff/draft-pr-closer@v0.2-alpha
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        days-before-close: 2
