# This is a basic workflow to help you get started with Actions

name: Thing

on: [push]

jobs:
  team_approval_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - name: Hello world action step
      id: hello
      uses: treiff/team-approvals-action@v1.0
      with:
        who-to-greet: 'blah blah'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
