name: Team Approval Action

on: [push]

jobs:
  team_approval_job:
    runs-on: ubuntu-latest
    name: Team Approval Labeler
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Get PR Status
      uses: treiff/team-approvals-action@v1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
